repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        language_version: python3
        args: ["--line-length", "100"]
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: pytest tests.py
        language: system
        types: [python]
        pass_filenames: false

      - id: linter
        name: Linter
        entry: flake8
        language: system
        types: [python]

