repos:
  - repo: local
    hooks:
      - id: run-tests
        name: Run tests
        entry: pytest tests.py
        language: system
        types: [python]
        pass_filenames: false

      - id: linter
        name: Linter
        entry: flake8
        language: system
        types: [python]

